### ISSUE TITLE
How to upload tarballs

### ISSUE THREAD

**Issue by from-nibly** [oclif/plugin-update#400]
It doesn't look like tarballs are supported for the updater.  In the documentation it says that the auto updater supports standalone tarballs but it's 100% unclear how the objects in the dist folder should be uploaded / how any of that works

https://oclif.io/docs/releasing

I'm not sure what the s3 templates are in @oclif/core.

If I run `DEBUG='*' my-cli update --available` it looks like it expects a file at

`${oclif.update.s3.host}/versions/tabc-linux-x64-tar-gz.json`

What is that file and how would it get generated? it doesn't seem to be generated by `oclif pack tarball`

does the `oclif upload tarballs` generate those files?

**Comment by RodEsp** [comment]
Hey @from-nibly, the docs are a little outdated, sorry about that but we're working on updating them.

In the meantime, in order to get `plugin-update` to work you have to upload the tarballs to an s3 bucket or s3 compatible storage using `oclif upload` as described in the [standalone tarball docs](https://oclif.io/docs/releasing#standalone-tarballs).

The `.json` file you mention above is a version index, this is what tells `plugin-update` what versions/channels are available and which release of the CLI they map to. They are put there by `oclif promote --indexes`.

Hopefully that answers your question for now!

**Comment by from-nibly** [comment]
Ok so then the docs should be changed cause they state that the host doesn't even need to be an see host. Or maybe I'm just confused by that statement?

**Comment by RodEsp** [comment]
It doesn't need to be the Amazon S3 service, but it should be compatible with the S3 api. So something like [MinIO](https://min.io/product/s3-compatibility) or [Linode Object Storage](https://www.linode.com/products/object-storage/) would work just fine.

**Comment by from-nibly** [comment]
Ahh ok. side note I am also running into this issue https://github.com/oclif/plugin-update/issues/379
